//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    using System.Windows.Forms;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Koordinat", Namespace="http://schemas.datacontract.org/2004/07/ServiceMtk_P2_20180140041")]
    [System.SerializableAttribute()]
    public partial class Koordinat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.iMatematika")]
    public interface iMatematika {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iMatematika/Tambah", ReplyAction="http://tempuri.org/iMatematika/TambahResponse")]
        int Tambah(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iMatematika/Tambah", ReplyAction="http://tempuri.org/iMatematika/TambahResponse")]
        System.Threading.Tasks.Task<int> TambahAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iMatematika/Kurang", ReplyAction="http://tempuri.org/iMatematika/KurangResponse")]
        int Kurang(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iMatematika/Kurang", ReplyAction="http://tempuri.org/iMatematika/KurangResponse")]
        System.Threading.Tasks.Task<int> KurangAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iMatematika/Kali", ReplyAction="http://tempuri.org/iMatematika/KaliResponse")]
        int Kali(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iMatematika/Kali", ReplyAction="http://tempuri.org/iMatematika/KaliResponse")]
        System.Threading.Tasks.Task<int> KaliAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iMatematika/Bagi", ReplyAction="http://tempuri.org/iMatematika/BagiResponse")]
        int Bagi(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iMatematika/Bagi", ReplyAction="http://tempuri.org/iMatematika/BagiResponse")]
        System.Threading.Tasks.Task<int> BagiAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iMatematika/TKoordinat", ReplyAction="http://tempuri.org/iMatematika/TKoordinatResponse")]
        ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.Koordinat TKoordinat(ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.Koordinat a, ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.Koordinat b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iMatematika/TKoordinat", ReplyAction="http://tempuri.org/iMatematika/TKoordinatResponse")]
        System.Threading.Tasks.Task<ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.Koordinat> TKoordinatAsync(ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.Koordinat a, ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.Koordinat b);
        Label Tambah(double angka1, double angka2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iMatematikaChannel : ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.iMatematika, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iMatematikaClient : System.ServiceModel.ClientBase<ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.iMatematika>, ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.iMatematika {
        
        public iMatematikaClient() {
        }
        
        public iMatematikaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iMatematikaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iMatematikaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iMatematikaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Tambah(int a, int b) {
            return base.Channel.Tambah(a, b);
        }
        
        public System.Threading.Tasks.Task<int> TambahAsync(int a, int b) {
            return base.Channel.TambahAsync(a, b);
        }
        
        public int Kurang(int a, int b) {
            return base.Channel.Kurang(a, b);
        }
        
        public System.Threading.Tasks.Task<int> KurangAsync(int a, int b) {
            return base.Channel.KurangAsync(a, b);
        }
        
        public int Kali(int a, int b) {
            return base.Channel.Kali(a, b);
        }
        
        public System.Threading.Tasks.Task<int> KaliAsync(int a, int b) {
            return base.Channel.KaliAsync(a, b);
        }
        
        public int Bagi(int a, int b) {
            return base.Channel.Bagi(a, b);
        }
        
        public System.Threading.Tasks.Task<int> BagiAsync(int a, int b) {
            return base.Channel.BagiAsync(a, b);
        }
        
        public ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.Koordinat TKoordinat(ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.Koordinat a, ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.Koordinat b) {
            return base.Channel.TKoordinat(a, b);
        }
        
        public System.Threading.Tasks.Task<ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.Koordinat> TKoordinatAsync(ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.Koordinat a, ServerdanClient_MuhammadMiqdadGhifar_041.ServiceReference1.Koordinat b) {
            return base.Channel.TKoordinatAsync(a, b);
        }
    }
}
